export const header = [
    {
      jam: "07.00 - 08.39",
      senin: "",
      selasa: "",
      rabu: "",
      kamis: "",
      jumat: "",
    },
    {
      jam: "07.00 - 09.20",
      senin: "",
      selasa: "",
      rabu: "",
      kamis: "",
      jumat: "",
    },
    {
      jam: "08.40 - 10.19",
      senin: "",
      selasa: "",
      rabu: "",
      kamis: "",
      jumat: "",
    },
    {
      jam: "09.30 - 11.59",
      senin: "",
      selasa: "",
      rabu: "",
      kamis: "",
      jumat: "",
    },
    {
      jam: "10.20 - 11.59",
      senin: "",
      selasa: "",
      rabu: "",
      kamis: "",
      jumat: "",
    },
    {
      jam: "12.50 - 14.19",
      senin: "",
      selasa: "",
      rabu: "",
      kamis: "",
      jumat: "",
    },
    {
      jam: "12.50 - 15.19",
      senin: "",
      selasa: "",
      rabu: "",
      kamis: "",
      jumat: "",
    },
    {
      jam: "14.30 - 16.19",
      senin: "",
      selasa: "",
      rabu: "",
      kamis: "",
      jumat: "",
    },
    {
      jam: "14.30 - 17.09",
      senin: "",
      selasa: "",
      rabu: "",
      kamis: "",
      jumat: "",
    },
    {
      jam: "15.30 - 18.00",
      senin: "",
      selasa: "",
      rabu: "",
      kamis: "",
      jumat: "",
    },
    {
      jam: "16.20 - 18.00",
      senin: "",
      selasa: "",
      rabu: "",
      kamis: "",
      jumat: "",
    },
  ]
