export const header = [
    {
      jam: "07.00 - 08.39",
      senin: "",
      selasa: "",
      rabu: "",
      kamis: "",
      jumat: "",
    },
    {
      jam: "07.50 - 08.39",
      senin: "",
      selasa: "",
      rabu: "",
      kamis: "",
      jumat: "",
    },
    {
      jam: "08.40 - 10.19",
      senin: "",
      selasa: "",
      rabu: "",
      kamis: "",
      jumat: "",
    },
    {
      jam: "09.30 - 11.59",
      senin: "",
      selasa: "",
      rabu: "",
      kamis: "",
      jumat: "",
    },
    {
      jam: "10.20 - 11.59",
      senin: "",
      selasa: "",
      rabu: "",
      kamis: "",
      jumat: "",
    },
    {
      jam: "10.30 - 12.09",
      senin: "",
      selasa: "",
      rabu: "",
      kamis: "",
      jumat: "",
    },
    {
      jam: "11.20 - 12.09",
      senin: "",
      selasa: "",
      rabu: "",
      kamis: "",
      jumat: "",
    },
    {
      jam: "12.50 - 15.19",
      senin: "",
      selasa: "",
      rabu: "",
      kamis: "",
      jumat: "",
    },
    {
      jam: "13.00 - 13.49",
      senin: "",
      selasa: "",
      rabu: "",
      kamis: "",
      jumat: "",
    },
    {
      jam: "13.00 - 14.49",
      senin: "",
      selasa: "",
      rabu: "",
      kamis: "",
      jumat: "",
    },
    {
      jam: "14.30 - 16.19",
      senin: "",
      selasa: "",
      rabu: "",
      kamis: "",
      jumat: "",
    },
    {
      jam: "14.45 - 16.24",
      senin: "",
      selasa: "",
      rabu: "",
      kamis: "",
      jumat: "",
    },
    {
      jam: "16.30 - 18.09",
      senin: "",
      selasa: "",
      rabu: "",
      kamis: "",
      jumat: "",
    },
    {
      jam: "17.20 - 18.09",
      senin: "",
      selasa: "",
      rabu: "",
      kamis: "",
      jumat: "",
    },
  ]
